apiVersion: v1
kind: Service
metadata:
  name: vllm-gpu
  namespace: llm-inference
  labels:
    app: vllm-gpu
spec:
  type: ClusterIP
  selector:
    app: vllm-gpu
  ports:
    - name: http
      port: 8000
      targetPort: 8000